version: '3.8'

services:
  bdd:
    container_name: mysql_database
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: ecommerce_app_database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      - "8080:3000"
    depends_on:
      - bdd

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mypass
      - REDIS_PORT=6379

  authentication_service:
    container_name: authentication_service
    ports:
      - "7000:7000"
    build:
      context: ./server/authentication-service
      dockerfile: Dockerfile
    environment:
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT=${REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT}
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_URL=${REACT_APP_SEARCH_SUGGESTION_SERVICE_URL}
    depends_on:
      - bdd
    env_file:
      - ".env"

  common-data-service:
    container_name: common-data-service
    ports:
      - "9050:9050"
    build:
      context: ./server/common-data-service
      dockerfile: Dockerfile
    environment:
      - REACT_APP_COMMON_DATA_SERVICE_PORT=9050
      - REACT_APP_COMMON_DATA_SERVICE_URL=http://localhost:9050
    depends_on:
      - bdd

  payment-service:
    container_name: payment-service
    ports:
      - "9000:9000"
    build:
      context: ./server/payment-service
      dockerfile: Dockerfile
    environment:
      - PAYMENT_SERVICE_PORT=9050
    depends_on:
      - bdd

  search-suggestion-service:
    container_name: search_suggestion-service
    ports:
      - "10000:10000"
    build:
      context: ./server/search-suggestion-service
      dockerfile: Dockerfile
    environment:
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT=10000
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_URL=http://localhost:10000
    depends_on:
      - bdd

volumes:
  db_data:
