FROM mysql:latest

ENV MYSQL_USER=mysqluser
ENV MYSQL_PASSWORD=mypass
ENV MYSQL_DATABASE=ecommerce_app_database
ENV MYSQL_ROOT_PASSWORD=mypass

EXPOSE 3306

CMD ["mysqld"]


# docker build -t blog .
# docker run -p 3333:8081 -d blog